
# Site Settings
title: Celebrante Diego Santos
url: 'celebrantedsantos.com.br'
logo: "/images/logo.jpg" # your photo (or logo) here
description:  Celebro o amor incondicional dos noivos e torno o grande dia da celebração deles ainda mais inesquecível e cheia de emoção!
tagline:  Celebrante de Casamentos, Bodas e Aniversários. Rua 7 de setembro, 666 - Centro ARARAS SP

google_site_verification: # https://search.google.com/search-console?resource_id=sc-domain%3Acelebrantedsantos.com.br

locale: pt_BR #en_US

author:
  name: Celebrante Diego Santos
  url: https://celebrandsantos.com.br/

instagram: diegosantoscelebrante

plugins:
  - jekyll-seo-tag

# Tracker
analytics : G-NWBC1EDVHS


sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

