# Site Settings
title: Celebrante Diego Santos
url: 'https://celebrantedsantos.com.br'
logo: "https://celebrantedsantos.com.br/images/logo.png" # your photo (or logo) here
description:  Celebro o amor incondicional dos noivos e torno o grande dia da celebração deles ainda mais inesquecível e cheia de emoção! . Rua 7 de setembro, 666 - Centro ARARAS SP
tagline:  Celebrante de Casamentos, Bodas e Aniversários em Araras SP e Região

#Colo Padrao
color: 0000000 #55A3BA

locale: pt_BR #en_US 
timezone:  America/Sao_Paulo

author:
  name: Celebrante Diego Santos
  url: https://celebrantedsantos.com.br

instagram: diegosantoscelebrante
social:
  name: diegosantoscelebrante
  links:
    - https://instagram.com/diegosantoscelebrante 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Tracker
webmaster_verifications:
  google: G-NWBC1EDVHS

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false