
# Site Settings
title: Celebrante Diego Santos
url: 'https://celebrandsantos.com.br'
logo: "logo.jpg?raw=true" # your photo (or logo) here
description:  Celebrante de Casamentos, Bodas e Aniversários.
  
instagram: diegosantoscelebrante

plugins:
  - jekyll-seo-tag

# Tracker
analytics: G-NWBC1EDVHS

sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "UTF-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false

